import Image from "next/image"
import { ProfileNavigationForSlug } from "@/components/profile-navigation"

const sections = [
  { id: "education", title: "Education", content: "Ph.D. Geography and Resource Development, University of Ghana (2013); M.Sc. Housing and Inner-City Revitalisation, IHS Rotterdam (2002); P.G. Dip. Architecture, KNUST (1999); B.Sc. (Hons) Design, KNUST (1994)." },
  { id: "research", title: "Research", content: "Climate change and nature-based solutions in African cities; everyday urbanism; flood resilience in earthen housing; thermal comfort in heritage buildings; architectural traditions, heritage, infrastructure, and postcolonial architecture in Africa. Projects include Tuwe Pamoja, Keeping Your Cool, Entanglement, Mobility and Improvisation, and Architecture and Planning in the Tropics." },
  { id: "publications", title: "Publications", content: "Published books and chapters with SOAS, Springer Nature, Afram Publications, and Nova Science, with articles in Energy and Buildings, The Journal of Architecture, Urban Studies, Journal of Urbanism, Urban Forum, Journal of African Cultural Studies, Feminist Africa, and other journals." },
  { id: "teaching", title: "Teaching", content: "African Urbanisms and related courses in African art, architecture, urban studies, and methods for constructing African art history." },
  { id: "leadership", title: "Leadership", content: "Associate editor for a special issue on Architecture and Soft Power in Third World Quarterly. Recipient of the Urban Studies Foundation International Fellowship (2022) and University of Liverpool Virtual Fellowship (2021)." },
  { id: "associations", title: "Associations", content: "Registered architect with the Ghana Institute of Architects and Architects Registration Council; member of the African Studies Association of Africa." },
]

export default function ProfessorIreneAppeaningAddoPage() {
  return <main className="mx-auto max-w-6xl px-6 py-10"><div className="grid gap-8 lg:grid-cols-[280px_1fr]"><aside><Image src="/images/professor-irene-appeaning-addo.jpg" alt="Professor Irene Appeaning Addo" width={600} height={750} className="w-full object-cover" /><div className="mt-5 space-y-3"><p className="text-sm font-semibold">Associate Professor of African Architecture</p><a className="text-sm text-primary underline" href="mailto:Iappeaningaddo@ug.edu.gh">Iappeaningaddo@ug.edu.gh</a><p className="text-sm text-muted-foreground">Section: Media and Visual Arts</p></div></aside><article><p className="mb-2 text-sm font-medium text-primary">Senior Member</p><h1 className="text-balance font-serif text-4xl font-bold">Professor Irene Appeaning Addo</h1><section id="profile" className="mt-8"><h2 className="mb-3 font-serif text-2xl font-bold">Profile</h2><p className="leading-7 text-muted-foreground">Irene Appeaning Addo is an Associate Professor of African Architecture at the Institute of African Studies, University of Ghana, Legon. Her work examines African architectural traditions, African cities, and postcolonial housing studies.</p></section>{sections.map((section) => <section id={section.id} key={section.id} className="mt-8"><h2 className="mb-3 font-serif text-2xl font-bold">{section.title}</h2><p className="leading-7 text-muted-foreground">{section.content}</p></section>)}<ProfileNavigationForSlug slug="professor-irene-appeaning-addo" /></article></div></main>
}
